device!{RCC |
     CR PLLCFG CFG CIR
     AHB1RST AHB2RST AHB3RST APB1RST APB2RST
     AHB1EN AHB2EN AHB3EN APB1EN APB2EN AHB1LPEN
     AHB2LPEN AHB3LPEN APB1LPEN APB2LPEN
     BDC
     CSR
     SSCG
     PLLI2SCFG
     PLLSAICFG
     DCKCFG
}
